---
permalink: online-help/reference-snapmirror-and-vault-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: SnapMirror 및 Vault 관계 이벤트는 잠재적인 문제를 모니터링할 수 있도록 비동기식 SnapMirror 및 Vault 관계 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= SnapMirror 및 Vault 관계 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror 및 Vault 관계 이벤트는 잠재적인 문제를 모니터링할 수 있도록 비동기식 SnapMirror 및 Vault 관계 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 충격 영역: 보호

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
비동기 미러와 볼트가 비정상(문서 대칭 복사됨 RelationshipUnhealthy)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트 연결이 끊어짐(문서:EvtMirrorVaultRelationshipStateBrokenoff)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 초기화 실패(문서 대칭 복사 VaultRelationshipInitializeFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 업데이트 실패(문서 대칭 복사. RelationshipUpdateFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 오류(문서 대칭 복사. RelationshipLagError)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 경고(문서 대칭 복사. RelationshipLagWarning)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트 재동기화 실패(문서 대칭 복사. RelationshipResyncFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류

|===