---
permalink: config/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 수 및 백업 일정을 설정할 수 있습니다. 매일 또는 매주 예약된 백업을 설정할 수 있습니다. 기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다. 
---
= 데이터베이스 덤프 백업에 대한 대상 및 스케줄 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 수 및 백업 일정을 설정할 수 있습니다. 매일 또는 매주 예약된 백업을 설정할 수 있습니다. 기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다.



== 시작하기 전에

* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 백업 경로로 정의한 위치에서 최소 150GB의 공간을 사용할 수 있어야 합니다.
+
Unified Manager 호스트 시스템 외부에 있는 원격 위치를 사용하는 것이 좋습니다.

* Linux 시스템에 Unified Manager를 설치할 때 ""jboss"" 사용자가 백업 디렉토리에 대한 쓰기 권한을 가지고 있는지 확인합니다.
* Unified Manager에서 15일의 기간별 성능 데이터를 수집하는 동안 새 클러스터를 추가한 직후에 백업 작업이 발생하도록 예약해서는 안 됩니다.




== 이 작업에 대해

첫 번째 백업은 전체 백업이므로 백업을 처음 수행할 때보다 더 많은 시간이 필요합니다. 전체 백업은 1GB가 넘고 3~4시간이 소요될 수 있습니다. 후속 백업은 증분 백업이므로 더 적은 시간이 필요합니다.

[NOTE]
====
증분 백업 파일 수가 백업에 할당된 공간에 비해 너무 많은 경우 새 전체 백업을 정기적으로 생성하여 이전의 전체 백업과 모든 하위 증분 파일을 대체할 수 있습니다. Linux 시스템에 Unified Manager가 설치되어 있는 경우, 다른 옵션으로 NetApp Snapshot 백업 방법을 사용할 수 있습니다.

====


== 단계

. 왼쪽 탐색 창에서 * 일반 * > * 데이터베이스 백업 * 을 클릭합니다.
. 데이터베이스 백업 * 페이지에서 * 백업 설정 * 을 클릭합니다.
. 백업 경로, 보존 수 및 스케줄에 대한 적절한 값을 구성합니다.
+
보존 수의 기본값은 10이며 무제한 백업을 생성하는 데 0을 사용할 수 있습니다.

. Scheduled Daily * 또는 * Scheduled Weekly * 버튼을 선택한 후 일정 세부 정보를 지정합니다.
. 적용 * 을 클릭합니다.




== 결과

데이터베이스 덤프 백업 파일은 일정에 따라 생성됩니다. 데이터베이스 백업 페이지에서 사용 가능한 백업 파일을 볼 수 있습니다.

* 관련 정보 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_start_a_new_Incremental_Backup_chain_within_ActiveIQ_Unified_Manager_versions_7.2_through_9.6["Active IQ Unified Manager 내에서 새 증분 백업 체인을 시작하는 방법"^]
